name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    uses: ./.github/workflows/python-quality.yml
    with:
      python-version: "3.12"

  tests:
    uses: ./.github/workflows/python-tests.yml

  build:
    uses: ./.github/workflows/python-build.yml
    with:
      verify-install: true
